name: clustering-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - scipy>=1.7.0
  - pyyaml>=6.0
  - tqdm>=4.62.0
  - plotly>=5.0.0
  - statsmodels>=0.13.0
  - pytest>=7.0.0
  - pip
  - pip:
    - fcmeans>=1.7.0
    - hydra-core>=1.1.0
    - loguru>=0.6.0
    - pytest-cov>=4.0.0